name: CI / CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python, Pipenv, and Dependencies
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Ensure Pipfile is Recognized
        run: ls -l && cat Pipfile  # Debugging step to check if Pipfile exists

      - name: Install Dependencies in Editable Mode
        run: pipenv install --dev -e .

      - name: Run Tests with Pytest
        run: pipenv run pytest -v
